version: '3.8'

services:
  # Backend сервис на Python с FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend_venv:/app/.venv
    environment:
      - ENVIRONMENT=development
    restart: unless-stopped
    networks:
      - app-network

  # Frontend сервис на Vue.js с Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${API_URL:-http://api.polyak.pp.ua:8000}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_venv:
